title:              "JUN BLOG"
email:              semineun@naver.com
description:        "하루하루 배워나가는 블로그"
author:             sJun
baseurl:            ""
url:                "https://drynod.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    drynod
#facebook_username:  StartBootstrap
#instagram_username:  
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
